# Generated by Django 3.1.7 on 2022-03-25 09:04

from django.db import migrations, models
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('body', models.TextField(blank=True, max_length=5000, verbose_name='text_body')),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('text_creature_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
