# Generated by Django 3.1.7 on 2022-12-29 22:41

from django.db import migrations, models
import django_admin_geomap


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('district', models.CharField(max_length=255, verbose_name='Район')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('color_status', models.CharField(choices=[('red', 'Красный цвет'), ('yellow', 'Желтый цвет'), ('green', 'Зеленый цвет')], default='red', max_length=15)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
